import FWCore.ParameterSet.Config as cms

inclusiveJetAnalyzer = cms.EDAnalyzer("HiInclusiveJetAnalyzer",

                                      jetTag = cms.InputTag("icPu5patJets"),
                                      jetPtMin = cms.double(5.0),
                                      genPtMin = cms.double(10.0),
                                      hardPtMin = cms.double(4),
                                      jetAbsEtaMax = cms.double(5.1),
                                      matchTag = cms.InputTag("akPu3PFpatJets"),
                                      genjetTag = cms.InputTag("iterativeCone5HiGenJets"),
                                      eventInfoTag = cms.InputTag("generator"),
                                      isMC = cms.bool(False), 
                                      fillGenJets = cms.bool(False),
                                      rParam = cms.double(0.5),
                                      trackTag = cms.InputTag("hiTracks"),
                                      useHepMC = cms.bool(False),
                                      useQuality = cms.bool(True),
                                      trackQuality  = cms.string("highPurity"),
                                      useCentrality = cms.untracked.bool(False),
                                      doLifeTimeTagging = cms.bool(False),
                                      doTrigger = cms.bool(False),
                                      L1gtReadout = cms.InputTag("gtDigis"),
                                      doGenTaus = cms.bool(False),
                                      doGenSym = cms.bool(False),
				      doSubJets = cms.bool(False),
				      doGenSubJets = cms.bool(False),
                                      doJetConstituents = cms.bool(False),
                                      doNewJetVars = cms.bool(False),
                                      doHiJetID = cms.bool(True),
                                      doStandardJetID = cms.bool(False),
                                      doSubEvent = cms.bool(False),
	                              jetIDWeight = cms.string("HeavyIonsAnalysis/JetAnalysis/data/JetID_TMVAClassification_BDTG_weights.xml"),       
 					
                                      hltTrgResults = cms.untracked.string("TriggerResults::HLT"),
                                      hltTrgNames  = cms.vstring('HLT_HIMinBiasHfOrBSC_Core',
                                                                           'HLT_HIJet35U',
                                                                           'HLT_HIJet35U_Core',
                                                                           'HLT_HIJet50U_Core'),
                                      vtxTag = cms.InputTag("hiSelectedVertex"),
                                      verbose = cms.bool(False),
                                      useVtx = cms.bool(False),
                                      useJEC = cms.bool(True),
                                      usePAT = cms.bool(True),
                                      doLifeTimeTaggingExtras = cms.bool(True),
                                      saveBfragments = cms.bool(True),
                                      skipCorrections = cms.bool(False),
                                      towersSrc = cms.InputTag("towerMaker"),
                                      doExtraCTagging = cms.bool(False),
                                      hltResName = cms.string("TriggerResults::HLT"),
                                      hltProcNames = cms.vstring('')
                                      )
